Fixes issue 1376
GetStream/stream-chat-react pull request #1380
Opened 2022-02-18 16:58 UTC by zacheryconverse

# Submit a pull request

### 🎯 Goal

Bug fix: Do not render message actions option if possible thread actions are disabled

### 🛠 Implementation details

If all permissions except `pin` were disabled, `showMessageActionsBox` would return a false positive because MessageActionsBox does not allow pins in 

### 🎨 UI Changes

![Screen Shot 2022-02-18 at 9 58 13 AM](https://user-images.githubusercontent.com/40873350/154727941-58782773-7712-475b-88d1-57af2c2337d9.png)
thread.

2022-02-18 19:28 UTC, petyosi requested changes
If I understand the three `ifs` correctly, the behavior can be handled by code that looks like this:

```tsx
const ACTIONS_NOT_WORKING_IN_THREAD = ['pin', 'react', 'reply']; // why reply?

export const showMessageActionsBox = (actions: MessageActionsArray, inThread?: boolean) => {
  if (actions.length === 0) {
    return false;
  }

  if (
    inThread &&
    actions.filter((action) => !ACTIONS_NOT_WORKING_IN_THREAD.includes(action)).length === 0
  ) {
    return false;
  }
//...
```

2022-02-18 21:30 UTC, zacheryconverse commented
Much better, yes this is correct. The reason for reply is because it refers to 'reply in thread' (not quote) - so of course you don't want to start a thread from in a thread.

2022-02-22 18:17 UTC, petyosi approved these changes

2022-02-22 18:18 UTC, merged

2022-03-17 18:30 UTC, petyosi commented
:tada: This PR is included in version 8.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/stream-chat-react/v/8.0.0)
- [GitHub release](https://github.com/GetStream/stream-chat-react/releases/tag/v8.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: