refactor: Use svg icon in ChannelHeader menu button
GetStream/stream-chat-react pull request #1392
Opened 2022-02-24 09:44 UTC by MartinCupela

### 🎯 Goal

Have menu icon rendered with SVG instead of HTML `<span>` elements. Allow to provide custom icon.

### 🛠 Implementation details

- create `MenuIcon` component used by default by `ChannelHeader`
- add `MenuIcon` prop to `ChannelHeaderProps`

2022-02-24 10:18 UTC, petyosi submitted a review, later dismissed
Code looks good, but you will need to document the prop here:

`docs/React/utility-components/channel-header.mdx`

2022-02-24 17:25 UTC, ambaldwin requested changes
This is a great addition. I left a couple comments, and we also need to update our docs with this new prop. docusaurus/docs/React/utility-components/channel-header.mdx.

2022-02-24 17:25 UTC, ambaldwin commented on src/components/ChannelHeader/ChannelHeader.tsx
> +  /** UI component do display menu icon, defaults to [MenuIcon](https://github.com/GetStream/stream-chat-react/blob/master/src/components/ChannelHeader/ChannelHeader.tsx)*/
UI component to* - typo here

2022-02-24 17:25 UTC, ambaldwin commented on src/components/ChannelHeader/ChannelHeader.tsx
> +import { MenuIcon as DefaultMenuIcon } from './icons';
This import should go above import { AvatarProps, Avatar as DefaultAvatar } from '../Avatar'; with a new line between it and surrounding imports. We group items by depth and abc.

2022-02-28 15:51 UTC, ambaldwin requested changes

2022-02-28 18:56 UTC, ambaldwin approved these changes

2022-03-07 07:42 UTC, merged

2022-03-17 18:30 UTC, petyosi commented
:tada: This PR is included in version 8.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/stream-chat-react/v/8.0.0)
- [GitHub release](https://github.com/GetStream/stream-chat-react/releases/tag/v8.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: