fix: filter out OG scraped images from attachments
GetStream/stream-chat-react pull request #1598
Opened 2022-05-17 18:08 UTC by arnautov-anton

### 🎯 Goal

Every time user updated message with URL with OG attachments, additional attachment (image) has been added to the array of attachments.

### 🛠 Implementation details

One of the solutions is to filter out any attachments which contain `og_scrape_url` property before submission so the BE can re-fetch them. The solution is fairly simple but does not work for when only attachments are updated thus not triggering BE re-fetch leaving the message without OG attachments.
Second solution is to keep all of the needed properties of the OG attachments (`title`, `title_link`, `author_name`, `text` and `og_scrape_url`) when updating the message but then we'd have to filter the OG attachments based on whether the `og_scrape_url` still exists within the message text.

Due to [BE implementation](https://www.notion.so/stream-wiki/OG-OpenGraph-URL-Enrichment-35bb3b6fdacf41e8b4dab59232a528aa) I opted for third solution which checks whether the text has been edited or not - if it was, the OG attachments get filtered out thus triggering re-enrichment.

### 🎨 UI Changes

(message after edit with two excessive attachments)
![image](https://user-images.githubusercontent.com/43254280/168880805-87aa84c6-4c1f-4b11-b746-4ebecf2fbade.png)

2022-05-24 10:17 UTC, MartinCupela requested changes
Nice work :)

2022-05-24 10:17 UTC, MartinCupela commented on e2e/edit-message.test.ts
> +      await user.clicks.Modal.removeAttachment(0);
```suggestion
      await user.clicks.EditMessageForm.removeAttachment(0);
```

2022-05-24 10:17 UTC, MartinCupela commented on src/components/MessageInput/hooks/useSubmitHandler.ts
> +      .filter((upload) => {
@arnautov-anton probably needs unit tests to check that the logic of `hasChanged` is covered?

2022-05-24 10:22 UTC, arnautov-anton commented on e2e/edit-message.test.ts
> +    expect(page.locator(selectors.attachmentCard)).toHaveCount(1);
Good point, still confused about the semantics. Will change this. :+1:

2022-05-24 20:18 UTC, MartinCupela submitted a review, later dismissed
Very nice refactor :+1:

2022-05-26 09:27 UTC, MartinCupela approved these changes

2022-05-26 09:28 UTC, merged

2022-06-03 11:08 UTC, petyosi commented
:tada: This PR is included in version 9.1.0 :tada:

The release is available on:
- [GitHub release](https://github.com/GetStream/stream-chat-react/releases/tag/v9.1.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/stream-chat-react/v/9.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: