add channel preview mute support
GetStream/stream-chat-react pull request #608
Opened 2020-11-13 19:38 UTC by DanC5

# Submit a pull request

## CLA

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request

2020-11-16 08:17 UTC, jaapbakker88 approved these changes

2020-11-17 06:06 UTC, mahboubii requested changes

2020-11-17 06:06 UTC, mahboubii commented on src/components/ChannelPreview/ChannelPreview.js
> +  }, [activeChannel, channel, isActive, muted]);
```suggestion
  }, [channel, isActive, muted]);
```

2020-11-17 06:06 UTC, mahboubii commented on src/components/ChannelPreview/ChannelPreview.js
> +  }, [activeChannel, channel, isActive, muted]);
```suggestion
  }, [channel, isActive, muted]);
```

2020-11-17 15:34 UTC, DanC5 commented
@mahboubii good catch on those dependencies, definitely didn't need to be there! So I think this is ready to go.

2020-11-17 17:27 UTC, mahboubii approved these changes

2020-11-17 17:28 UTC, merged