Css variables
GetStream/stream-chat-react pull request #927
Opened 2021-05-18 17:39 UTC by yetieaterxb1

# Submit a pull request

## CLA

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request

2021-06-23 14:24 UTC, DanC5 commented on src/styles/NewChannel.scss
>  .str-chat__new-channel {
doesn't look like the styles in this file are applied anywhere so we should delete

2021-06-23 14:24 UTC, DanC5 commented on src/styles/Panel.scss
>    bottom: calc(100%);
doesn't look like the styles in this file are applied anywhere so we should delete

2021-06-23 14:24 UTC, DanC5 commented on src/styles/ReadState.scss
>    position: absolute;
doesn't look like the styles in this file are applied anywhere so we should delete

2021-06-23 14:36 UTC, DanC5 commented on src/styles/_variables.scss
> +  --blue-alice: #e9f2ff; //keep
why some of these say keep

2021-06-23 15:26 UTC, ambaldwin commented on src/styles/_variables.scss
> +  --primary-color: #{$secondary-color};
primary color is set to secondary-color?

2021-06-23 15:32 UTC, ambaldwin requested changes

2021-06-23 15:32 UTC, ambaldwin commented on src/styles/_variables.scss
> +  --primary-color: #{$secondary-color};
actually, disregard the above note, and just add a comment to the file here to say why it's being set this way!

2021-06-24 20:52 UTC, DanC5 approved these changes

2021-06-24 21:34 UTC, merged